### ISSUE TITLE
Clarify about cross version 0-RTT via Compatible Version Negotiation

### ISSUE THREAD

**Issue by flano-yuki** [quicwg/quic-v2#14]
Thank you for this work.

Can quic v2 server accept a v1 0-RTT packet via Compatible Version Negotiation?

If I understand correctly, The [version negotiation specification](https://quicwg.org/version-negotiation/draft-ietf-quic-version-negotiation.html#name-interaction-with-0-rtt) says that "future versions will determine how to handle it." Even if the server accepts v1 packets as is, I would think the handling needs to be described in v2.

**Comment by kazu-yamamoto** [comment]
Developers are actually puzzled.
See https://github.com/quicwg/version-negotiation/issues/68

**Comment by martinthomson** [comment]
Moving the discussion here, I think that 0-RTT is not as clear-cut as it seems.

When doing a compatible upgrade from v1 to v2, a server makes the switch when it processes the ClientHello (that is, all Initial packets from the client to a first approximation).  It is relatively easy for the server to make the switch cleanly at that point because it doesn't need to read any more Initial packets and all other packets will be v2 from then on.

A client makes the switch based on seeing a v2 packet.  It might receive some v1 Initial packets, but the one containing a ServerHello will be v2.  If the client is sending 0-RTT packets, it might need to send them until it receives all of the Handshake packets from the server.  That is, it might be some time.

For a client in that state, it doesn't really make sense to switch to sending v2 0-RTT packets, but if it doesn't it will be intermixing transmission of v1 0-RTT packets and v2 Handshake packets.  This is awkward because there is no clean cut-over.

In my implementation, I also have to deal with stack integration issues that make installing the right 0-RTT keys difficult.

I ultimately opted to just reject 0-RTT if there was a version change.  The number of cases in which you might want to use 0-RTT and you don't already know what version the server wants to use are very limited.  Basically, this only happens if you are doing 0-RTT across an upgrade of the server.  Losing 0-RTT in that case seems tolerable.
