### ISSUE TITLE
Different version number

### ISSUE THREAD

**Issue by martinduke** [quicwg/quic-v2#4]
@martinthomson wants to use some other version number, not 2. I'd have to retitle the draft, but other than that I don't have a strong feeling about it.

**Comment by martinduke** [comment]
Upon further reflection, this is a pretty fundamental question: are QUIC versions incremental, where in general version N comes after N-1 and is implied to be "better", or are they randomly spread over the space with no clear temporal or quality relationship?

**Comment by kazuho** [comment]
> are QUIC versions incremental, where in general version N comes after N-1 and is implied to be "better", or are they randomly spread over the space with no clear temporal or quality relationship?

I think this is the framing that we should use for reaching a resolution.

The reason we chose "HTTP/3" as the name for the HTTP binding for QUIC is because people tend to believe that increments on version number represent something better. It'd be hard if not impossible to change that perception.

Comparing to that, this "v2" draft is not something meant to be better than v1 - it is merely an alternative wire encoding of v1.

Based on that, I tend to agree with @martinthomson; it would be less confusing to people if we choose a large random number than "v2."
